lib: [
  "_build/install/default/lib/mux-proto/META" {"META"}
  "_build/install/default/lib/mux-proto/opam" {"opam"}
  "_build/install/default/lib/mux-proto/mux__Client.cmi"
  "_build/install/default/lib/mux-proto/mux__Client.cmx"
  "_build/install/default/lib/mux-proto/mux__Client.cmt"
  "_build/install/default/lib/mux-proto/client.ml"
  "_build/install/default/lib/mux-proto/mux__Headers.cmi"
  "_build/install/default/lib/mux-proto/mux__Headers.cmx"
  "_build/install/default/lib/mux-proto/mux__Headers.cmt"
  "_build/install/default/lib/mux-proto/mux__Headers.cmti"
  "_build/install/default/lib/mux-proto/headers.mli"
  "_build/install/default/lib/mux-proto/mux.cmi"
  "_build/install/default/lib/mux-proto/mux.cmx"
  "_build/install/default/lib/mux-proto/mux.cmt"
  "_build/install/default/lib/mux-proto/mux.ml-gen"
  "_build/install/default/lib/mux-proto/mux__S.cmi"
  "_build/install/default/lib/mux-proto/mux__S.cmx"
  "_build/install/default/lib/mux-proto/mux__S.cmt"
  "_build/install/default/lib/mux-proto/s.ml"
  "_build/install/default/lib/mux-proto/mux__Server.cmi"
  "_build/install/default/lib/mux-proto/mux__Server.cmx"
  "_build/install/default/lib/mux-proto/mux__Server.cmt"
  "_build/install/default/lib/mux-proto/server.ml"
  "_build/install/default/lib/mux-proto/mux.cma"
  "_build/install/default/lib/mux-proto/mux.cmxa"
  "_build/install/default/lib/mux-proto/mux.a"
  "_build/install/default/lib/mux-proto/mux.cmxs"
]
doc: [
  "_build/install/default/doc/mux-proto/README.md"
  "_build/install/default/doc/mux-proto/LICENSE.md"
]
